using WinUIXamlDesigner.Models;

namespace WinUIXamlDesigner.Services;

public sealed class WriteBackService
{
    private readonly XamlDocumentService _xaml;
    private readonly CSharpEventService _csharp;

    public WriteBackService(XamlDocumentService xaml, CSharpEventService csharp)
    {
        _xaml = xaml;
        _csharp = csharp;
    }

    public async Task WriteAsync(GridDocument model, GridDocument? baseline = null, CancellationToken cancellationToken = default)
    {
        var newXaml = _xaml.Serialize(model);
        string? newCs = null;
        if (model.CodeBehindPath is not null && File.Exists(model.CodeBehindPath))
        {
            var currentCs = await File.ReadAllTextAsync(model.CodeBehindPath, cancellationToken);
            newCs = currentCs;
            var oldById = baseline?.Nodes.ToDictionary(n => n.Id) ?? new Dictionary<Guid, ControlNode>();
            var currentIds = model.Nodes.Select(n => n.Id).ToHashSet();

            foreach (var deleted in oldById.Values.Where(n => !currentIds.Contains(n.Id) && n.EventWasAutoGenerated && !string.IsNullOrWhiteSpace(n.EventName)))
                newCs = _csharp.UpdateEventHandler(newCs, deleted, deleted.EventName, null, true);

            foreach (var node in model.Nodes.Where(n => !string.IsNullOrWhiteSpace(n.EventName)))
            {
                oldById.TryGetValue(node.Id, out var old);
                var oldEvent = old?.EventWasAutoGenerated == true ? old.EventName : null;
                var newEvent = node.EventName;
                if (oldEvent is not null && newEvent is not null && oldEvent != newEvent)
                    newCs = _csharp.UpdateEventHandler(newCs, node, oldEvent, newEvent, false);
                else if (oldEvent is null)
                    newCs = _csharp.UpdateEventHandler(newCs, node, null, newEvent, false);
            }
        }
        await CommitPairAsync(model.FilePath, newXaml, model.CodeBehindPath, newCs, cancellationToken);
        model.OriginalXamlText = newXaml;
        model.IsDirty = false;
    }

    public async Task CommitRenameAsync(GridDocument before, GridDocument after, ControlNode beforeNode, ControlNode afterNode, CancellationToken cancellationToken = default)
    {
        var newXaml = _xaml.Serialize(after);
        string? newCs = null;
        if (after.CodeBehindPath is not null && File.Exists(after.CodeBehindPath))
        {
            var currentCs = await File.ReadAllTextAsync(after.CodeBehindPath, cancellationToken);
            var oldEvent = beforeNode.EventWasAutoGenerated ? beforeNode.EventName : null;
            var newEvent = afterNode.EventName;
            newCs = _csharp.UpdateEventHandler(currentCs, afterNode, oldEvent, newEvent, beforeNode.EventWasAutoGenerated && string.IsNullOrWhiteSpace(newEvent));
        }
        await CommitPairAsync(after.FilePath, newXaml, after.CodeBehindPath, newCs, cancellationToken);
        after.OriginalXamlText = newXaml;
        after.IsDirty = false;
    }

    public static Task CommitRawPairAsync(string xamlPath, string newXaml, string? csPath, string? newCs, CancellationToken cancellationToken = default)
        => CommitPairAsync(xamlPath, newXaml, csPath, newCs, cancellationToken);

    private static async Task CommitPairAsync(string xamlPath, string newXaml, string? csPath, string? newCs, CancellationToken cancellationToken)
    {
        var oldXaml = await File.ReadAllTextAsync(xamlPath, cancellationToken);
        var oldCs = csPath is not null && File.Exists(csPath) ? await File.ReadAllTextAsync(csPath, cancellationToken) : null;
        var xamlTemp = xamlPath + ".designer-tmp";
        var csTemp = csPath is null ? null : csPath + ".designer-tmp";
        try
        {
            await File.WriteAllTextAsync(xamlTemp, newXaml, cancellationToken);
            if (csTemp is not null && newCs is not null)
                await File.WriteAllTextAsync(csTemp, newCs, cancellationToken);
            File.Move(xamlTemp, xamlPath, true);
            if (csPath is not null && csTemp is not null && newCs is not null)
                File.Move(csTemp, csPath, true);
        }
        catch
        {
            try { if (File.Exists(xamlTemp)) File.Delete(xamlTemp); } catch { }
            try { if (csTemp is not null && File.Exists(csTemp)) File.Delete(csTemp); } catch { }
            try { await File.WriteAllTextAsync(xamlPath, oldXaml, cancellationToken); } catch { }
            if (csPath is not null && oldCs is not null)
            {
                try { await File.WriteAllTextAsync(csPath, oldCs, cancellationToken); } catch { }
            }
            throw;
        }
    }
}
